export type DressCheckerIssueCode =
  | "PGVECTOR_MISSING"
  | "EMBEDDINGS_MISSING"
  | "EMBEDDINGS_MISSING_CATEGORY"
  | "AI_PROFILES_MISSING"
  | "AI_PROFILES_INCOMPLETE"
  | "OPENAI_UNAVAILABLE"
  | "OPENAI_KEY_MISSING"
  | "QUERY_EMBEDDING_FAILED"
  | "VECTOR_SEARCH_EMPTY"
  | "VECTOR_SEARCH_FAILED"
  | "SEARCH_DEGRADED_HASH"
  | "UNEXPECTED_SEARCH_ERROR";
