export const BOOKING_PRIVATE_MEDIA_TYPES = {
  ID_PROOF: "ID_PROOF",
  JEWELLERY_SELECTION: "JEWELLERY_SELECTION",
  ORDER_PHOTO: "ORDER_PHOTO",
  DELIVERY_EVIDENCE: "DELIVERY_EVIDENCE",
  RETURN_EVIDENCE: "RETURN_EVIDENCE",
  INCOMPLETE_RETURN: "INCOMPLETE_RETURN",
  DAMAGE_EVIDENCE: "DAMAGE_EVIDENCE",
  FITTING_PHOTO: "FITTING_PHOTO",
  MEASUREMENT_IMAGE: "MEASUREMENT_IMAGE",
  OTHER_PRIVATE_BOOKING_MEDIA: "OTHER_PRIVATE_BOOKING_MEDIA",
} as const;

export type BookingPrivateMediaType =
  (typeof BOOKING_PRIVATE_MEDIA_TYPES)[keyof typeof BOOKING_PRIVATE_MEDIA_TYPES];

export const BOOKING_PRIVATE_MEDIA_STATUS = {
  ACTIVE: "ACTIVE",
  PENDING_DELETE: "PENDING_DELETE",
  DELETED: "DELETED",
  DELETE_FAILED: "DELETE_FAILED",
} as const;

export type BookingPrivateMediaStatus =
  (typeof BOOKING_PRIVATE_MEDIA_STATUS)[keyof typeof BOOKING_PRIVATE_MEDIA_STATUS];
