ALTER TABLE "booking_items" ADD COLUMN IF NOT EXISTS "fitting_charges" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "total_fitting_charges" DOUBLE PRECISION NOT NULL DEFAULT 0;
